### ISSUE TITLE
Close, Benson, Saupe, Clapham, Butler (2020)

### ISSUE THREAD

**Issue by nuest** [codecheckers/register#13]
**Repository**: https://science.sciencemag.org/content/suppl/2020/04/22/368.6489.420.DC1

**Paper**: https://science.sciencemag.org/content/368/6489/420.full

**Certificate**: `YYYY-NNN`

------

I just want to celebrate these authors putting the effort in to provide good instructions and publishing _a tarball of their workflow Docker image as supplemental material_. However, the article itself is not open access.

- Supplemental PDF with a bunch of figures: https://science.sciencemag.org/content/sci/suppl/2020/04/22/368.6489.420.DC1/aay8309_Close_SM.pdf
- Excerpt from the README of `Data S1` archive:
  > # Instructions for running R analysis for Close et al. (in review) The spatial structure of Phanerozoic marine animal diversity
  > WARNING: this analysis consumes a lot of copmuting resources when run on the full (i.e., not cut-down) occurrence dataset. When I (Roger Close) ran the analysis, I always did so on an Ubuntu Linux machine with 32 CPU cores and 256 GB RAM. Even then it took ~4 hours to run. Even though I put substantial efforts into optimising memory usage, the analysis failed to run on a machine with 32 cores and only 128 GB RAM, because it ran out of memory. However, you can run the analysis on a substantially cut-down occurrence dataset by uncommenting the line `# ss_data <- ss_data %>% sample_frac(size = 0.25)` in the file `master-script.R`.

**Comment by nuest** [comment]
@sje30 What do you think about an unsolicited community review of a non-open access article?

**Comment by sje30** [comment]
Just for the record - we have emailed the authors to query if an OA version of the paper is/will be available.

**Comment by nuest** [comment]
@sje30 did you hear back from the authors?

**Comment by sje30** [comment]
no, not yet.  I will follow up.

**Comment by nuest** [comment]
Paper is available at https://core.ac.uk/download/pdf/324096972.pdf though no CC-style license, "print one copy, non-commercial".

@sje30 Do you reckon this is "open enough" ?

**Comment by nuest** [comment]
We have enough checks by now with better collaborators, and I don't like the license terms:

![image](https://user-images.githubusercontent.com/1325054/195012015-1a97db07-7009-429d-9ae2-10c5389812c2.png)
