### ISSUE TITLE
Zaunier, Udovicic, Spitschan - 2024

### ISSUE THREAD

**Issue by nuest** [codecheckers/register#132]
Accepted for publication, currently in contact with author and editor if CODECHECK can be mentioned in the paper.

@sje30 volunteered as codechecker.

**Preprint:** https://www.researchsquare.com/article/rs-3771881/v1

**Repository**: https://github.com/tscnlab/ZaunerEtAl_PLoS_ONE_2024 | https://zenodo.org/records/14035243

**Certificate**: `2024-018`

**Comment by sje30** [comment]
I have good news @JZauner


after the normal wrangling with packages, I only hit one error, which I'll document below, and then I managed to get the same figures as originally provided in the manuscript.

I may well be finishing the certificate tomorrow live during the workshop at Rotterdam.

**Comment by sje30** [comment]
## Set up

To start, I moved the original figures and html to new names, so I could compare my version with the originals:

```
 cp PowerCalc.html PowerCalc-orig.html
 mv Figures Figures-orig
 mkdir Figures
```

 I then reduced n_samples (line 15, yaml, from 1000 to 10)

and then ran the document:

    quarto render PowerCalc.qmd 

Note: this wasn't reported in the readme (it may well be obvious how to do the rendering).

**Comment by sje30** [comment]
# Installation problem

I liked the use of the pacman package, which was new to me.  However, I did get some error messages on the first run:

```

 ERROR: dependency ‘cards’ is not available for package ‘gtsummary’
* removing ‘/Users/stephen/NOBACKUP/RLIB/gtsummary’

ERROR: dependencies ‘minqa’, ‘nloptr’ are not available for package ‘lme4’
* removing ‘/Users/stephen/NOBACKUP/RLIB/lme4’

ERROR: dependency ‘nloptr’ is not available for package ‘lme4’
* removing ‘/Users/stephen/NOBACKUP/RLIB/lme4’

** byte-compile and prepare package for lazy loading
Note: wrong number of arguments to 'ceiling' 
```

Reading the source file, I saw the note about the Matrix package.  Having seen errors with lme4, I thought it would be sensible to follow the advice to update Matrix and lme4:

```

oo <- options(repos = "https://cran.r-project.org/")
install.packages("Matrix", type = "source")
install.packages("lme4", type = "source")
options(oo)
library(lme4)
library(lmerTest)
```

This worked.  And then the main packages loaded okay.

## Failure to load the LightLogR package from github

I got this error:

```
p_load_gh("tscnlab/LightLogR")
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/tscnlab/LightLogR/tarball/HEAD' failed
Warning messages:
1: In p_install_gh(package, dependencies, ...) :
  The following may have incorrect capitalization specification:

LightLogR
2: In p_load_gh("tscnlab/LightLogR") : 
Failed to install/load:
tscnlab/LightLogR
```

I couldn't see what was run, but luckily the package is also available
on github, and that did install fine for me:

```
install.packages("LightLogR")
Installing package into ‘/Users/stephen/NOBACKUP/RLIB’
(as ‘lib’ is unspecified)
also installing the dependencies ‘fontBitstreamVera’, ‘fontLiberation’, ‘fontquiver’, ‘jpeg’, ‘gdtools’, ‘officer’, ‘gridtext’, ‘warp’, ‘flextable’, ‘ggsci’, ‘ggtext’, ‘slider’
```


That took about 30 minutes to make progress (Eurostar wifi was having problems downloading the packages though...)

**Comment by sje30** [comment]
## Running the code

After installations finished, the code seemed to work, until this chunk:

```
22/37 [nonwear summary]   
Error in gtsummary::tbl_summary(., statistic = list(NonWear ~ "{min} - {max}"),  : 
  Error processing `label` argument.
! Can't select columns that don't exist. ✖ Column `valid_Day` doesn't exist.
ℹ Select among columns "Id", "Season", "Day", and "NonWear"
Calls: .main ... withRestartList -> withOneRestart -> docall -> do.call -> fun

Quitting from lines 421-469 [nonwear summary] (PowerCalc.qmd)
Execution halted

```

TO debug this, I needed to run the document using Markdown, rather than quarto (as intermediate variables are kept:

```
rmarkdown::render("PowerCalc.qmd")
```

which allowed me to at least debug; I do not understand why valid_Day is supposed to be missing from the tibble, as it seems to be there:


```
> Nonwear_summary %>%
+ gtsummary::tbl_summary(
+ statistic = list(NonWear ~"{min} - {max}"),
+ label = list(NonWear ~ "Non-Wear Time",
+ valid_Day ~ "Valid Days"),
+ by = valid_Day)
Error in `gtsummary::tbl_summary()`:
! Error processing `label` argument.
! Can't select columns that don't exist. ✖ Column `valid_Day` doesn't exist.
ℹ Select among columns "Id", "Season", "Day", and "NonWear"
Run `rlang::last_trace()` to see where the error occurred.

> colnames(Nonwear_summary)
[1] "Id"        "Season"    "Day"       "NonWear"   "valid_Day"

```

My *hack* to get the code working was simply to remove the 2nd element of the list from the label argument (see my code); this then allowed the code to complete.

Rendering time is just a few minutes.

**Comment by sje30** [comment]
```
library(pacman)
packages <- c("quarto", "tidyverse", "broom", "cowplot", "gt", "gtsummary", 
              "gghighlight", "patchwork", "readxl", "lme4", "lmerTest",
              "ggridges", "osfr")

p_load(packages, character.only = TRUE)

load("Nonwear_summary.Rda")
Nonwear_summary %>% 
   gtsummary::tbl_summary(
     statistic = list(NonWear ~"{min} - {max}"),
     label = list(NonWear ~ "Non-Wear Time",
                  valid_Day ~ "Valid Days"),
     by = valid_Day)

```

**Comment by sje30** [comment]
## Summary

figures regenerated fine.   Bootstrapping differences are seen in figure 4 -- my answers are based on far fewer samples.

**Comment by mischewu** [comment]
I encountered an error on line 160 of the master script. 

Running the following code:
```
LLdata <- import$Actiwatch_Spectrum(files[german_encoding], 
                                    locale = locale(encoding="latin1"),
                                    tz = tz, na = na_s, auto.id = auto.id,
                                    column_names = column_names)
```


returns the following error:

```
Error in `purrr::map()`:
ℹ In index: 1.
Caused by error in `detect_starting_row()`:
! Could not find a line with this order of column names in the file: '08963_MES8_1A_2015-01-13_06_00_00_Neue_Analyse.csv'.
 Please check the correct order and spelling of the given columns: 'Line.*Date.*Time.*Off Wrist.*Activity.*Marker.*White Light.*Red Light.*Green Light.*Blue Light.*Sleep Wake.*Interval Status'
Backtrace:
  1. import$Actiwatch_Spectrum(...)
  8. purrr::map(...)
  9. purrr:::map_("list", .x, .f, ..., .progress = .progress)
 13. LightLogR (local) .f(.x[[i]], ...)
 14. LightLogR:::detect_starting_row(...)
 15. base::stop(...)
```

**Comment by JZauner** [comment]
Hi @sje30 and @mischewu ,

thanks for the great work reproducing the results! 
@sje30:
I don't know why there are troubles with the packages, and will have to look at the Rda object for the valid_Day issue.
@mischewu : The error you are encountering is to a change in LightLogR after version 0.3.8. 
As this is the version on CRAN, @sje30 did not encounter the problem. The safest way would be to change LightLogR from github install to CRAN install, specifying the version to 0.3.8:

line 36 would then change to:
`packages_github <- c("steffenhartmeyer/lightdosimetry")`

and then two new lines:
`install.packages("LightLogR", version="0.3.8")`
`library(LightLogR)`

It would be interesting to see whether @mischewu gets the same error regarding the valid_Day column.

**Comment by mischewu** [comment]
Thanks, the suggestions fixed it. It runs smoothly now, until indeed the error with the valid_day column. That is, without the workaround proposed by @sje30. 

```
Error in `gtsummary::tbl_summary()`:
! Error processing `label` argument.
! Can't select columns that don't exist. ✖ Column `valid_Day` doesn't exist.
ℹ Select among columns "Id", "Season", "Day", and "NonWear"
Backtrace:
 1. Nonwear_summary %>% ...
 2. gtsummary::tbl_summary(...)
```

**Comment by nuest** [comment]
:rocket: https://zenodo.org/records/14235113

**Comment by nuest** [comment]
@sje30 Let me know when the codecheck.yml is ready and I'll render the register locally - the CI still does not work because of rate limits.

Save travels!

**Comment by sje30** [comment]
https://github.com/codecheckers/ZaunerEtAl_PLoS_ONE_2024/blob/main/codecheck.yml

is up now.

just home...

**Comment by sje30** [comment]
p.s. there is also a package called 'pak' -- it is supposed to just install, not load, packages, but seems to quite comprehensive.

**Comment by nuest** [comment]
Article is published: https://doi.org/10.1371/journal.pone.0308768

Unfortunately there is only a generic reference to CODECHECK but the certificate is not cited.

![image](https://github.com/user-attachments/assets/b51dbda8-d85c-488d-b151-b6998c440a7a)

@JZauner I assume the editorial team did simply not react to your email from Nov 29 ?

**Comment by JZauner** [comment]
They sent an email the day after with the info that the manuscript was formally accepted and would go into the final internal editorial, which I interpreted as a positive signal. Unfortunately, they did not add the reference as you wrote. I wrote to the academic editor to ask for a formal revision and will update with any feedback.
