### ISSUE TITLE
Brunsdon and Comber (2020)

### ISSUE THREAD

**Issue by nuest** [codecheckers/register#15]
**Repository**: https://github.com/codecheckers/OpeningPractice

**Certificate**: `2020-011`

@sje30 I did this codecheck as part of my activity as a regular reviewer, but until we have some collaboration with the journal (telco with editors pending), I'd say this is still a "community check". Let me know if you disagree.

@sje30 I started the new "id assigned" label to more easily find out the next ID. Any other idea how to streamline this?

**Comment by nuest** [comment]
Zenodo draft is ready, waiting for DOI from publisher. Remaining steps

- [ ] add paper DOI
- [ ] update the report PDF
- [ ] publish Zenodo record

**Comment by nuest** [comment]
https://zenodo.org/record/3873153

**Comment by nuest** [comment]
- [ ] update register

**Comment by nuest** [comment]
https://zenodo.org/record/3981253

**Comment by sje30** [comment]
how come this isn't in the CODECHECK community on zenodo (yet)?
