### ISSUE TITLE
Render docs on CI

### ISSUE THREAD

**Issue by nuest** [codecheckers/register#17]
Currently, the output rendered to HTML and Markdown require manual interaction, see https://github.com/codecheckers/register#files-in-this-repository

This could be done in a CI process and therefore limit the manual work. Just the CSV has to be updated then. Invalid configuration files should result in no update of the outputs.

**Comment by nuest** [comment]
Note this probably requires to Login with GitHub to not hit a rate limit.

**Comment by sje30** [comment]
so in future, I just edit the csv, and do not need to remake manually the html?  cool.

**Comment by nuest** [comment]
Sorry, this does not work yet. But yes, that would be the goal in the future.

**Comment by nuest** [comment]
It works! https://github.com/codecheckers/register/commit/b179fe9ebd389a6d2ebdd220666d8abce69e63a7

Reverting that double entry now.
