### ISSUE TITLE
Add link to the paper from the register rendering

### ISSUE THREAD

**Issue by nuest** [codecheckers/register#23]
@sje30 What do you think, should we add a link to the paper from the register website? Or do we want to guide people to it via the report?

**Comment by nuest** [comment]
Maybe we should have an extra landing page per certificate that has this link.

https://codecheck.org.uk/register/cert/2020-001

or

https://codecheck.org.uk/register/2020-001

**Comment by sje30** [comment]
On Tue, Feb 09 2021, Daniel Nüst wrote:

> Maybe we should have an extra landing page per certificate that has this link.
>
> https://codecheck.org.uk/register/cert/2020-001
>
> or
>
> https://codecheck.org.uk/register/2020-001

Great idea -- slightly prefer the latter URL.

S

**Comment by angelina-momin** [comment]
@sje30 I discussed what the url for the certs would be like with Daniel in the meeting last Friday. We both think it would be best to keep it to "https://codecheck.org.uk/register/certs/2020-001" at the moment for the sake of consistency. Other files are organised under subfolders well like "venues" and "codecheckers" resulting in links "https://codecheck.org.uk/register/venues/name" and "https://codecheck.org.uk/register/codecheckers/name".

Would you be okay with us keeping the link as "https://codecheck.org.uk/register/certs/2020-001"? We can always change it later, along with the other fields, if necessary.

**Comment by sje30** [comment]
Yes, I'm happy to keep the links as-is.

**Comment by nuest** [comment]
We link to the certificate page in the first column `Certificate`, i.e. make `2020-001` a clickable link just as the other columns.

**Comment by nuest** [comment]
#88 adds the paper title to the table and it will link to the paper, so it also solves this issue.

The discussion here about the certificate URL is relevant for #37 and the above decision noted there.
