### ISSUE TITLE
Roger Bivand JGSY-D-19-00087

### ISSUE THREAD

**Issue by rsbivand** [codecheckers/register#24]
**Repository**: ... https://github.com/rsbivand/JGSY-D-19-00087

Current submission: 
[JGSY-D-19-00087_R2.pdf](https://github.com/codecheckers/register/files/5135891/JGSY-D-19-00087_R2.pdf)

**Comment by nuest** [comment]
Thanks! I'll be the codechecker for this one.

**Comment by nuest** [comment]
https://github.com/codecheckers/JGSY-D-19-00087

**Comment by nuest** [comment]
**Certificate**: `2020-017`

**Comment by nuest** [comment]
Reserved DOI on Zenodo: `10.5281/zenodo.4003848`
