### ISSUE TITLE
Certificate page as part of the register

### ISSUE THREAD

**Issue by nuest** [codecheckers/register#37]
This is then base for an "overlay journal" kind of website, see codecheckers/discussion#29.

New pages needed:

https://codecheck.org.uk/certificate/2020-001 or https://codecheck.org.uk/register/2020-001 or https://cdchck.org/cert/2020-001

- have multi-page JPG or a GIF as preview of the certificate
  - see https://eddelbuettel.github.io/rticles-gallery/ (code at https://github.com/eddelbuettel/rticles-gallery/blob/master/script.R#L60 using `convert`)
- get the paper abstract via some nice API - Crosscite?
  - https://github.com/ropensci/rcrossref/blob/master/R/cr_abstract.R
  - https://github.com/CrossRef/rest-api-doc/issues/98
- get the full citation from DOI
  - https://github.com/ropensci/rcrossref/blob/master/R/cr_cn.r
- include semantic metadata in the HTML head, cf. https://schema.org/ and how OJS embed Dublin Core metadata
- page has a preview image/rendering
  - https://developer.twitter.com/en/docs/twitter-for-websites/cards/guides/getting-started
  - https://github.blog/2013-01-24-github-now-supports-twitter-cards/

Would probably also solve codecheckers/register#23.

### Layout

Somewhere between ReScience C and JOSS:

![image](https://user-images.githubusercontent.com/1325054/115361338-c670b500-a1c0-11eb-914a-d98b827dcb44.png)

![image](https://user-images.githubusercontent.com/1325054/115361636-0df74100-a1c1-11eb-9719-67044708d36a.png)

**Comment by nuest** [comment]
Should this URL also be used for the link behind the badge? The DOI is certainly more sustainable.

**Comment by angelina-momin** [comment]
@nuest can you specify how you want to display the multi-page JPEG? The idea I had was having buttons to navigate through the different jpeg images of the certificate. This is the html I created so far. Can you let me know what you and @sje30 think?

**Comment by sje30** [comment]
this looks very cool.

Couple of points in my mind:

1. Going forward, if we switch to having our codecheck package use quarto templates to generate both html and pdf versions of certs, would that be helpful to this process (or make it redundant).  I'm wary that our codecheck.Rmd approach works but is very clunky and would like to do something a bit nicer / cross-platform.
2. is it easy to always get the abstract of the underlying paper?  If not, I'd suggest not prioritising work on where the abstract goes (it looks nice where it is).

**Comment by nuest** [comment]
Thanks for the nice mockups!

Re. placement: Looks fine! I think we could, below the abstract, also show the **codecheck summary**, which we have in the codecheck.yml file. That would give us some nice indexing in search engines, I hope.

Re. full citation: I would put that at the top, because it also takes care of showing the certificate authors. Not sure if #82 would be overkill now or actually easier than coming up with a full citation ourselves.

**Comment by nuest** [comment]
One more thing re. Stephens comment on switching to Quarto: In that case it might be good now to integrate the preview based on an HTML file that is stored somewhere. For now, the HTML will just show the first page of the PDF as a preview, and later we can simply store the Quarto output in the HTML file (I generously use the term "simple" here ;-) ).

**Comment by nuest** [comment]
Zenodo has a rate limit, see https://developers.zenodo.org/#update-schedule

Therefor, let's limit our requests to Zenodo to one per second.

**Comment by nuest** [comment]
There was a discussion in #23 about the URL and we agreed on the following format:

`codecheck.org.uk/register/certs/2020-001`

This puts certs on the same level as other resources, e.g., venues, checkers.

**Comment by nuest** [comment]
The reason for these two variants: sometimes codecheckers use the GitHub-Zenodo-Integration to deposit the whole repository, with the PDF in it, and sometimes codecheckers render a PDF locally and upload only that to Zenodo, possibly with additional material (like a zip file of the repo) next to it. I prefer to keep it this flexible and leave room for the codecheckers to choose what makes most sense for the check at hand.

Therefore: I think we need a little bit of flexibility on the side of the register here.

However, I'm actually not really keen on storing copies of all the PDFs in the register... would you say it's feasible to embed PDFs only where there is one directly accessible via URL, e.g. in https://zenodo.org/api/records/13364677 one can use https://zenodo.org/api/records/13364677/files/codecheck.pdf/content and in other cases (i.e., where there is a ZIP file) just show a "no preview available, please visit http://zenodo...." ?

**Comment by nuest** [comment]
**Work in progress at https://github.com/codecheckers/codecheck/pull/71**
