### ISSUE TITLE
Barto, Sutton, Anderson

### ISSUE THREAD

**Issue by nuest** [codecheckers/register#4]
One more from the "classical neuroscience papers" collection, see #2 

https://github.com/codecheckers/Barto-Sutton-Anderson-1983

**Comment by nuest** [comment]
Certificate: `2020-004`

**Comment by sje30** [comment]
I can do this one as a check of the new codecheck package.

**Comment by nuest** [comment]
I have not started, but maybe you could do #5 or #6 because those require Matlab?

**Comment by sje30** [comment]
yes!

**Comment by nuest** [comment]
Codecheck completed: https://zenodo.org/record/3827371

**Comment by nuest** [comment]
Just need to update the register.

**Comment by nuest** [comment]
Note for the record, no action needed here — leaving this issue closed.

As part of the register-wide Zenodo metadata curation (#205) the certificate for 2020-004 needed its metadata brought in line with the CODECHECK [community curation policy](https://zenodo.org/communities/codecheck/curation-policy). Editing the existing record was refused by Zenodo with `Files are not enabled`, an API limitation on some older deposits, so the change was made by publishing a **new version** of the record instead:

* previous version: https://doi.org/10.5281/zenodo.3827371
* new version: https://doi.org/10.5281/zenodo.22109800

The concept DOI is unchanged, so the existing citation keeps resolving to the latest version. The certificate PDF is identical; only the metadata differs.

The `report` DOI in the repository's `codecheck.yml` is updated in codecheckers/Barto-Sutton-Anderson-1983#1.
