### ISSUE TITLE
AGILE 2022 reproducibility review 

### ISSUE THREAD

**Issue by nuest** [codecheckers/register#41]
The AGILE reproducibility review 2022 has completed 16 (!!!) reproductions in line with the CODECHECK principles. This issue is just to reserve the certificate IDs while I'm preparing the CODECHECK configuration files.

@sje30 Please start with 2022-018 if you begin a new check in the coming days.

**Certificate**: `2022-002` to `2022-017`

**Comment by nuest** [comment]
Citation | CODECHECK certificate ID
---------- | ----------
Cai, G., and Pan Y.: Understanding the Imperfection of 3D point Cloud and Semantic Segmentation algorithms for 3D Models of Indoor Environment, AGILE GIScience Ser., 3, 2, https://doi.org/10.5194/agile-giss-3-2-2022 | 2022-002
Cai, H., Xin, Y., Martin, H., and Raubal, M.: Optimizing Electric Vehicle Charging Schedules Based on Probabilistic Forecast of Individual Mobility, AGILE GIScience Ser., 3, 3, https://doi.org/10.5194/agile-giss-3-3-2022 | 2022-003
Favreau, J.-M., and Kalsron, J.: What are intersections for pedestrian users?, AGILE GIScience Ser., 3, 4, https://doi.org/10.5194/agile-giss-3-4-2022 | 2022-004
Georgati, M., Monteiro, J., Martins, B., and Keßler, C.: Spatial Disaggregation of Population Subgroups Leveraging Self-Trained Multi-Output Gradient Boosted Regression Trees, AGILE GIScience Ser., 3, 5, https://doi.org/10.5194/agile-giss-3-5-2022 | 2022-005
Iskandaryan, D., Di Sabatino, S., Ramos, F., and Trilles, S.: Exploratory Analysis and Feature Selection for the Prediction of Nitrogen Dioxide, AGILE GIScience Ser., 3, 6, https://doi.org/10.5194/agile-giss-3-6-2022 | 2022-006
Liu, Z., Janowicz, K., Cai, L., Zhu, R., Mai, G., and Shi, M.: Geoparsing: Solved or Biased? An Evaluation of Geographic Biases in Geoparsing, AGILE GIScience Ser., 3, 9, https://doi.org/10.5194/agile-giss-3-9-2022 | 2022-007
Niers, T., Stenkamp, J., Jakuschona, N. P., Bartoschek, T., and Schade, S.: Benchmarking Invasive Alien Species Image Recognition Models for a Citizen Science Based Spatial Distribution Monitoring, AGILE GIScience Ser., 3, 10, https://doi.org/10.5194/agile-giss-3-10-2022 | 2022-008
Nuhn, E., König, F., and Timpf, S.: "Landmark Route": A Comparison to the Shortest Route, AGILE GIScience Ser., 3, 12, https://doi.org/10.5194/agile-giss-3-12-2022 | 2022-009
Qamaz, Y., Schwering, A., and Bistron, J.: Experimental evaluation of using BLE beacon for outdoor positioning in GPS-denied environment, AGILE GIScience Ser., 3, 13, https://doi.org/10.5194/agile-giss-3-13-2022 | 2022-010
Sharma, A., Farhadloo, M., Li, Y., Kulkarni, A., Gupta, J., and Shekhar, S.: Understanding COVID-19 Effects on Mobility: A Community-Engaged Approach, AGILE GIScience Ser., 3, 14, https://doi.org/10.5194/agile-giss-3-14-2022 | 2022-011
Shin, H., Cagnina, C., and Basiri, A.: The Impact of Built Environment on Bike Commuting: Utilising Strava Bike Data and Geographically Weighted Models, AGILE GIScience Ser., 3, 15, https://doi.org/10.5194/agile-giss-3-15-2022 | 2022-012
Syed, M. A., Arsevska, E., Roche, M., and Teisseire, M.: GeoXTag: Relative Spatial Information Extraction and Tagging of Unstructured Text, AGILE GIScience Ser., 3, 16, https://doi.org/10.5194/agile-giss-3-16-2022 | 2022-013
Van Damme, M.-D., and Olteanu-Raimond, A.-M.: A method to produce metadata describing and assessing the quality of spatial landmark datasets in mountain area, AGILE GIScience Ser., 3, 17, https://doi.org/10.5194/agile-giss-3-17-2022 | 2022-014
Wiedemann, N., Martin, H., and Raubal, M.: Unlocking social network analysis methods for studying human mobility, AGILE GIScience Ser., 3, 19, https://doi.org/10.5194/agile-giss-3-19-2022 | 2022-015
Zhao, P., Li, A., Pilesjö, P., and Mansourian, A.: A machine learning based approach for predicting usage efficiency of shared e-scooters using vehicle availability data, AGILE GIScience Ser., 3, 20, https://doi.org/10.5194/agile-giss-3-20-2022 | 2022-016
Zourlidou, S., Golze, J., and Sester, M.: Traffic Regulation Recognition using Crowd-Sensed GPS and Map Data: a Hybrid Approach, AGILE GIScience Ser., 3, 22, https://doi.org/10.5194/agile-giss-3-22-2022 | 2022-017

**Comment by sje30** [comment]
noted!
