### ISSUE TITLE
Fix register rendering in GH action

### ISSUE THREAD

**Issue by nuest** [codecheckers/register#43]
https://github.com/codecheckers/register/runs/6869861565?check_suite_focus=true

![image](https://user-images.githubusercontent.com/1325054/173449327-31584899-3ab3-49af-9db1-4bf7d9f97f03.png)

**Comment by nuest** [comment]
@angelina-momin Please check if this is still an issue.

**Comment by angelina-momin** [comment]
@nuest I no longer see the error in the run.
