### ISSUE TITLE
Larisch

### ISSUE THREAD

**Issue by nuest** [codecheckers/register#5]
https://github.com/codecheckers/Larisch-reproduction

**Comment by nuest** [comment]
Certificate: `2020-005`

**Comment by IainDaviesMaths** [comment]
Published on zenodo

**Comment by nuest** [comment]
@IainDaviesMaths — reopening this issue with a request, sorry for the noise on an old thread.

We now check every certificate in the register against the [CODECHECK community curation policy](https://zenodo.org/communities/codecheck/curation-policy) as part of the register rendering, and are working through the records that do not yet follow it (see #205). Most were corrected centrally, but your Zenodo record cannot be edited because the deposit belongs to your account, despite it being part of the community.

So this one needs you. The changes for [zenodo.org/records/3959175](https://zenodo.org/records/3959175):

| Field | Current | Should be |
| --- | --- | --- |
| Title | `CODECHECK certificate 2020-005` | `CODECHECK Certificate 2020-005` |
| Publisher | `Zenodo` | `CODECHECK Community on Zenodo` |
| Related work | — | Relation `Reviews`, DOI `10.5281/zenodo.3538217`, resource type Publication |
| Alternate identifier | — | `http://cdchck.science/register/certs/2020-005`, scheme `URL` |
| Alternate identifier | — | `cdchck.science/register/certs/2020-005`, scheme `Other` |

All of these are editable via *Edit* on the record page; none of them create a new version or change the DOI.

If you would rather not do it by hand, you can grant edit access instead and we will apply it for you: on the record page click **Share**, then under the **People** tab click **Add people**, search the **User** field for `nuest` or `daniel.nuest@tu-dresden.de`, set **Access** to **Can edit** and click **Add**. (If the search doesn't find that account, just say so here and we'll sort it out.) Either way, please close this issue again when done — or say so here and we will.

Thanks for the original codecheck, and sorry to come back to it six years later.

**Comment by nuest** [comment]
One more item for this record, sorry: the licence should be **CC-BY 4.0**, currently it is `Other (open)`. This is a decision of the CODECHECK initiative for all certificates in the register, so no judgement needed on your side — it can be set under *Edit* → *Licence* on the record page, alongside the changes above.
