### ISSUE TITLE
Add list of all codecheckers

### ISSUE THREAD

**Issue by nuest** [codecheckers/register#71]
Currently you have to know the ORCID of a checker to construct the URL from knowing the ORCID.

There should be a list of all checkers, sorted by ORCID, at https://codecheck.org.uk/register/codecheckers/

The formats should be HTML, so https://codecheck.org.uk/register/codecheckers/index.html, and JSON: https://codecheck.org.uk/register/codecheckers/index.json. Both listing should include the clear name and a link resp. URL of the codechecker's personal register in the respective format.

(Open new issues for possible extensions, such as showing the number of checks for each individual, ...)

**Comment by angelina-momin** [comment]
@nuest this is what I have at the moment. Can you lmk if you would like any changes?
The codechecker name links to the codecheck website with all their codechecks.
the orcid ID links to their orcid pages.

![image](https://github.com/user-attachments/assets/1293bbb5-8b42-4131-8e2a-710b5c692f41)

**Comment by nuest** [comment]
Thanks, @angelina-momin - looks good!

Firsr suggestion I have is that you also link the values "No. of checks" column to the codechecker page that lists these checks.

Second idea: Do you have an idea how you could integrate the number of checkers? The headline seems a bit too strong for that. But it would be nice to read that number instead of trying to count through the rows. A "sum row" seems an option but might be confusing without explanation.

Maybe a sentence after the headline, before the table?

_"In total, N codecheckers contributed M checks."_

If we get that to work easily, we could have similar data points in the other overview pages. I can create an issue for that next week, if the second suggestion is unclear.

**Comment by angelina-momin** [comment]
Accidentally closed the issue

**Comment by nuest** [comment]
Looks great! Thanks for the changes!

Just a minor question: how is the list sorted? My guess: they are ordered by the ID (effectively the date) of the first CODECHECK that they did.

**Comment by angelina-momin** [comment]
Currently, the order of the codecheckers on this page follows the order of the certificates and their respective codecheckers in register.csv. Let me know if that's okay with you. 

I was thinking we can create a separate issue for "sort by" feature which would be a nice enhancement

**Comment by nuest** [comment]
Yes, please do create that issue!

**Comment by nuest** [comment]
https://codecheck.org.uk/register/codecheckers/ :tada:
