### ISSUE TITLE
Add a list of all venues

### ISSUE THREAD

**Issue by nuest** [codecheckers/register#80]
https://codecheck.org.uk/register/venues/ should have a list of links to all existing venues.

https://codecheck.org.uk/register/conference should have a list of links to all existing conferences.

**Comment by nuest** [comment]
It would probably be nice to extend both HTML and JSON rendering, just to have one machine readable list of all items here, too. I think a Markdown document does not make that much sense.

**Comment by angelina-momin** [comment]
Can you let me know what you think of this?
Each of the venue name links to the register table associated with the venue. 
It seems counterintuitive because one would think that clicking on the name would link to the website of the venu but found this to be the best way to put it.

![image](https://github.com/user-attachments/assets/c444e97a-6de3-4e76-8459-fd0dead6aea9)

**Comment by nuest** [comment]
Sorry for my brevity, replying on the go...

Let's make the No. of checks column clickable ab link to the list of the checks of that venue. The small numbers might get lost if they are links... Maybe we append a "(see all checks)" in each line?

I'm happy for the name column to link to the home page of the venue, however, we do not have this stored yet. Related to #84. I suggest to keep the link as it is now an revisit after implementing #84.
How does  that sound to you?

----------------- 

The first column could link to a list of all venues of the same type. Can you please create a separate issue? Thanks!

**Comment by angelina-momin** [comment]
Hi Daniel about your last comment:
1) I implemented your suggestion on the "No. of codechecks" column 

2) I kept the "venue name" as it is i.e links to the codecheck of that venue.

Please let if you would like more changes and if not I will send you a review request for the PR.

![image](https://github.com/user-attachments/assets/08fd1a50-2f3b-4ae7-a316-72846e7083c3)

**Comment by nuest** [comment]
No more changes for now! Good work.

Re. the journal names: I think we can better revisit that when we think about the detailed metadata for venues, see #84.

**Comment by nuest** [comment]
https://codecheck.org.uk/register/venues/
