### ISSUE TITLE
Use singular/plural only in API resources

### ISSUE THREAD

**Issue by nuest** [codecheckers/register#81]
Currently there is "venues" but "community", "codecheckers" but "journal".

**Comment by angelina-momin** [comment]
@nuest Do you have a preference for any particular API type? Since REST API is the most common API type I am thinking of implementing plural API resources which is the REST API's convention.

**Comment by nuest** [comment]
@angelina-momin Yes, plural because of REST convention is fine.

**Comment by angelina-momin** [comment]
@nuest and do you want to keep "register" as "register" or "registers" in 
"https://codecheck.org.uk/register/venues/journal/"

But then if pluralized not sure what to do with "register" here:
"https://codecheck.org.uk/register/"

**Comment by nuest** [comment]
There will every only be one register, that one should stay singular.
