### ISSUE TITLE
Use only lower case in URLs or implement redirect

### ISSUE THREAD

**Issue by nuest** [codecheckers/register#85]
https://codecheck.org.uk/register/venues/journal/GigaByte/ works but https://codecheck.org.uk/register/venues/journal/gigabyte/ does not. This is possibly error prone.

We could add permanent redirects to the lower case variants, but I prefer to simply not use any capital letters in the URLs.

**Comment by angelina-momin** [comment]
PR for this fix:
Codecheck PR [#55](https://github.com/codecheckers/codecheck/pull/55)
Register PR [#98](https://github.com/codecheckers/register/pull/98)

Put this fix in the same PR as issue [#89](https://github.com/codecheckers/register/issues/89)
