### ISSUE TITLE
Remove "Repository" column in the register table HTML and replace it with the title of the paper

### ISSUE THREAD

**Issue by nuest** [codecheckers/register#88]
The repository information is not helpful for browsing, but the title is. The title is be a link to the paper DOI.

We can keep the CSV file consistent with the table.

**Comment by angelina-momin** [comment]
@nuest just to clarify, are these the changes that you would like:
1. In the `register.csv` you would like the "Repository" column to be replaced by the paper titles
2. In the `index.html` you would like the paper titles to be hyperlinks to the actual paper

**Comment by nuest** [comment]
@angelina-momin Very good that you ask to clarify this.

Re 1.: I do _not_ intend to have this change in `register.csv`, because we need the information of the repository in there since that is the location of the `codecheck.yml`. I was only thinking about the user facing information. Ideally, the JSON would include more details. I think to make the register more user friendly to browser, we need more and more seperation between the HTML version and the other more "API-like" renderings.

Re. 2.: Yes, linking the paper via the DOI from the title, please.

Re. 3.: About he title... "Paper" seems generic enough to also cover preprints, so that's good. "Codechecked work" seems a bit clunky for everybody except me who uses codecheck as a verb weekly... Let's go with "Paper title" for now!

I would imagine to keep the `register.csv` as the core data set, which is the one we edit when we add a new check, and then derive all other documents from it. I know we create a discrepancy between the HTML rendering and the CSV file that is linked below it, though. I can live with that for now, and then solve this via #102 which will generate a more useful CSV file, which we can then link to from below the HTML table.

**Comment by nuest** [comment]
Please do both, (3).

The reference should be free text, for example when a paper is not yet published but we decide to publish the codecheck. It is not the norm, bit the processing should not break. The validation of codecheck.yml files in the R package should already reflect this.

Yes, this means some things, like linking to the paper from the HTML, does not work.

Trying to extract the right link from the field is a rabbit hole I do not want us to go down to. Then I'd rather add an extra field `reference-text` and require that `reference` always is a DOI or so.

After hardening the code, the particular field should only contain the correct DOI that is shown in the linked page.

---------

Re. markdown content: use the option that is least work (probably matching the HTML?)

Re. JSON content: should be as extensive as possible to support programmatic access to our metadata. So probably leave as is for now, unless changes are quick. Then we can extend it in connection with #102.
