### ISSUE TITLE
Add a list of all checks for each venue type

### ISSUE THREAD

**Issue by angelina-momin** [codecheckers/register#93]
Related to this issue for a webpage with a list of venues PR #80 

For each venue type there will be a page listing all the codechecks for this venue type.

**Comment by nuest** [comment]
@angelina-momin I changed he title - is that what you meant?

**Comment by angelina-momin** [comment]
Hi Daniel, yes that is what I meant. My bad, thanks for the correction!

**Comment by angelina-momin** [comment]
Solved by PR [#54](https://github.com/codecheckers/codecheck/pull/54) and [#99](https://github.com/codecheckers/register/pull/99)
